### ISSUE TITLE
Error fetching from remote

### ISSUE THREAD

**Issue by subhassh** [GreenDelta/lca-collaboration-server-docker#2]
# Error description

I tried to install collaboration server in my university remote server and use it with my openLCA installation at home pc but after connecting to the server the commands like fetch, push threw an error.

NOTE: when I did the same with a local installation of the collaboration server in another pc of my local home network, it works without error.

# Steps to reproduce

1. https://github.com/GreenDelta/lca-collaboration-server-docker/tree/main -  installed this in a remote server.
2. accessing the collaboration server webapp and initial setups are successful
3. successfully connected to the server from openLCA in client pc

4. clicking on commit works.

5. clicking on fetch, push, and pull doesn't work and produces the same error.

# Attached files
![image](https://github.com/user-attachments/assets/5659fb05-e2d0-4f92-8138-ab6d3b08c730)

![image](https://github.com/user-attachments/assets/0b669063-5641-4771-a82f-db79c8756a36)

# openLCA error message

Error fetching from remote

# Installation details

* openLCA version: 2.3.0
* operating system: Windows 11
* os architecture: amd64
* os version: 10.0
* native libraries loaded: false
* with sparse matrix support: false

# Full error stack trace

```
org.eclipse.jgit.api.errors.TransportException: invalid advertisement of <!DOCTYPE html><html lang="en"><head><base href="/"/><title>LCA Collaboration Server</title><meta http-equiv="expires" content="0"/><meta name="viewport" content="width=device-width, initial-scale=1"/><meta name="fragment" content="!"/><link rel="shortcut icon" type="image/x-icon" href="images/favicon.ico"/><link rel="stylesheet" type="text/css" href="css/styles.css?timestamp=1734021754153"/></head><body class="public-mode"><div id="announcements"><table><tbody><tr><td id="announcement-message"></td></tr></tbody></table></div><header class="navbar-fixed-top" id="cs-header"><div class="logo-container"><a href=""><img class="logo" src="images/logo.png" title="Logo"/></a></div><div class="content-container"><div class="header-content"><h4 id="header-title"></h4></div></div><div id="user-menu"><div id="global-search-bar"></div></div></header><nav id="main-navigation"></nav><div id="main"><div class="full-size"> <div class="center"></div></div></div><div id="maintenance-notification"></div><script src="js/main.js?timestamp=1734021754153"></script></body></html>
at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:249)
at org.openlca.git.actions.GitFetch.run(GitFetch.java:36)
at org.openlca.git.actions.GitFetch.run(GitFetch.java:13)
at org.openlca.app.collaboration.navigation.actions.Actions$GitRemoteRunner.run(Actions.java:147)
at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: org.eclipse.jgit.errors.PackProtocolException: invalid advertisement of <!DOCTYPE html><html lang="en"><head><base href="/"/><title>LCA Collaboration Server</title><meta http-equiv="expires" content="0"/><meta name="viewport" content="width=device-width, initial-scale=1"/><meta name="fragment" content="!"/><link rel="shortcut icon" type="image/x-icon" href="images/favicon.ico"/><link rel="stylesheet" type="text/css" href="css/styles.css?timestamp=1734021754153"/></head><body class="public-mode"><div id="announcements"><table><tbody><tr><td id="announcement-message"></td></tr></tbody></table></div><header class="navbar-fixed-top" id="cs-header"><div class="logo-container"><a href=""><img class="logo" src="images/logo.png" title="Logo"/></a></div><div class="content-container"><div class="header-content"><h4 id="header-title"></h4></div></div><div id="user-menu"><div id="global-search-bar"></div></div></header><nav id="main-navigation"></nav><div id="main"><div class="full-size"> <div class="center"></div></div></div><div id="maintenance-notification"></div><script src="js/main.js?timestamp=1734021754153"></script></body></html>
at org.eclipse.jgit.transport.TransportHttp$HttpObjectDB.invalidAdvertisement(TransportHttp.java:1517)
at org.eclipse.jgit.transport.TransportHttp$HttpObjectDB.readAdvertisedImpl(TransportHttp.java:1483)
at org.eclipse.jgit.transport.TransportHttp.newDumbConnection(TransportHttp.java:482)
at org.eclipse.jgit.transport.TransportHttp.getConnection(TransportHttp.java:372)
at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:467)
at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:153)
at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:105)
at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1458)
at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:238)
... 4 more

```

**Comment by subhassh** [comment]
After hours of debugging and looking into source code, trying to change parameters and stuff like that, nothing worked, as I decided to gave up on docker version and look into normal installation instructions, especially in the configuration instructions from https://www.openlca.org/lca-collaboration-server-2-configuration-guide/ there is important line that says
### After the repositories root directory was changed, a restart of the application is required 
Once I closed the running docker and restarted it, everything works!.
